- name: Create Users with SSH access and sudo without password
  hosts: my-hosts 
  become: true

  vars:
    users:
      - satish
      - kiran

  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        groups: admin
        state: present 
      loop: "{{ users }}"

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', './' + item + '_public_key.pub') }}"
        state: present
      loop: "{{ users }}"

    - name: Allow admin users to sudo without a password
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
