- name: Create Users with SSH access and sudo without password
  hosts: my-hosts 
  become: true

  vars:
    users:
      - satish
      - kiran

  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        state: present 
      loop: "{{ users }}"

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', './' + item + '_public_key.pub') }}"
        state: present
      loop: "{{ users }}"

    - name: Allow sudo without password
      lineinfile:
        dest: "/etc/sudoers"
        line: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        insertafter: EOF
      loop: "{{ users }}"
