---
- hosts: "my-hosts"
  vars:
    users:
    -  "satish"
    -  "kiran"
  tasks:
  - name: "Ensure group admin exists"
    group:
      name: admin
      state: present
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "admin"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', './'+ item + '_public_key.pub') }}"
    with_items: "{{ users }}"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
