- name: Delete Users
  hosts: my-hosts 
  become: true

  vars:
    users:
      - satish
      - kiran

  tasks:
    - name: Delete users
      user:
        name: "{{ item }}"
        state: absent
        remove: true 
      loop: "{{ users }}"

