- name: Delete Users
  hosts: my-hosts 
  become: true

  vars:
    users:
      - username: satish
      - username: kiran

  tasks:
    - name: Delete users
      user:
        name: "{{ item.username }}"
        state: absent
        remove: true 
      loop: "{{ users }}"

